name: Generate GitHub Profile Summary Cards

on:
  schedule:
    - cron: "17 3 * * *"   # atualiza 1x por dia
  workflow_dispatch:       # permite rodar manualmente
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: simionidev
          THEME: city_lights

      - name: Commit files
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: update profile summary cards"
            git push
          fi
